### ISSUE TITLE
Problem using on ubuntu 14.04 x64

### ISSUE THREAD

**Issue by pward123** [brainling/cpuid-node#4]
It looks like the module is looking for cpuid.node when the build under ubuntu is creating a cpuid.a

```
savi@ubunut-server-14:~/server$ cat /etc/*release | grep VERSION
VERSION="14.04.3 LTS, Trusty Tahr"
VERSION_ID="14.04"
savi@ubunut-server-14:~/server$ uname -a
Linux ubunut-server-14 3.19.0-30-generic #33~14.04.1-Ubuntu SMP Tue Sep 22 09:27:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
savi@ubunut-server-14:~/server$ npm install cpuid
npm WARN package.json SAVIServer@1.0.0 No repository field.
-
> cpuid@0.1.2 install /home/savi/server/node_modules/cpuid
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/savi/server/node_modules/cpuid/build'
  CC(target) Release/obj.target/libcpuid/deps/libcpuid/libcpuid/asm-bits.o
  CC(target) Release/obj.target/libcpuid/deps/libcpuid/libcpuid/cpuid_main.o
  CC(target) Release/obj.target/libcpuid/deps/libcpuid/libcpuid/libcpuid_util.o
  CC(target) Release/obj.target/libcpuid/deps/libcpuid/libcpuid/rdtsc.o
  CC(target) Release/obj.target/libcpuid/deps/libcpuid/libcpuid/recog_amd.o
  CC(target) Release/obj.target/libcpuid/deps/libcpuid/libcpuid/recog_intel.o
  AR(target) Release/obj.target/deps/libcpuid/cpuid.a
  COPY Release/cpuid.a
  CXX(target) Release/obj.target/cpuid/src/cpuid.o
make: Leaving directory `/home/savi/server/node_modules/cpuid/build'
cpuid@0.1.2 node_modules/cpuid
```

```
savi@ubunut-server-14:~/server$ nodejs
> var cpuid = require('cpuid')
cpuid.node seems to not have been built. Run npm install.
Error: Cannot find module '../build/default/cpuid'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/savi/server/node_modules/cpuid/lib/cpuid.js:7:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by pward123** [comment]
This turned out to be a configuration issue on the machine being used
