### ISSUE TITLE
Upgrade to the new version of nodejs 4.x.x, and Nan 2.xx

### ISSUE THREAD

**Issue by daldegam** [brainling/cpuid-node#5]
Hi,

You can upgrade you code to the new version of nodejs 4.x.x, and Nan 2.xx?

My env is:
```
Mac OS El Capitan

node --version 
v4.1.1

node-gyp --version
v3.0.3
```

thank you :)

output on node-gyp rebuild
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.1.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/cpuid/src/cpuid.o
../src/cpuid.cc:48:17: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("fpu"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_FPU]));
                              ^
../src/cpuid.cc:48:24: error: 'String' does not refer to a value
                features->Set(NanNew<String>("fpu"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_FPU]));
                                     ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2081:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../src/cpuid.cc:48:40: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("fpu"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_FPU]));
                                                     ^
../src/cpuid.cc:48:47: error: 'Boolean' does not refer to a value
                features->Set(NanNew<String>("fpu"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_FPU]));
                                                            ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2044:17: note: declared here
class V8_EXPORT Boolean : public Primitive {
                ^
../src/cpuid.cc:49:17: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("virtualModeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_VME]));
                              ^
../src/cpuid.cc:49:24: error: 'String' does not refer to a value
                features->Set(NanNew<String>("virtualModeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_VME]));
                                     ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2081:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../src/cpuid.cc:49:57: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("virtualModeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_VME]));
                                                                      ^
../src/cpuid.cc:49:64: error: 'Boolean' does not refer to a value
                features->Set(NanNew<String>("virtualModeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_VME]));
                                                                             ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2044:17: note: declared here
class V8_EXPORT Boolean : public Primitive {
                ^
../src/cpuid.cc:50:17: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("debuggingExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_DE]));
                              ^
../src/cpuid.cc:50:24: error: 'String' does not refer to a value
                features->Set(NanNew<String>("debuggingExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_DE]));
                                     ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2081:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../src/cpuid.cc:50:55: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("debuggingExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_DE]));
                                                                    ^
../src/cpuid.cc:50:62: error: 'Boolean' does not refer to a value
                features->Set(NanNew<String>("debuggingExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_DE]));
                                                                           ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2044:17: note: declared here
class V8_EXPORT Boolean : public Primitive {
                ^
../src/cpuid.cc:51:17: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("pageSizeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_PSE]));
                              ^
../src/cpuid.cc:51:24: error: 'String' does not refer to a value
                features->Set(NanNew<String>("pageSizeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_PSE]));
                                     ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2081:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../src/cpuid.cc:51:54: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("pageSizeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_PSE]));
                                                                   ^
../src/cpuid.cc:51:61: error: 'Boolean' does not refer to a value
                features->Set(NanNew<String>("pageSizeExtension"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_PSE]));
                                                                          ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2044:17: note: declared here
class V8_EXPORT Boolean : public Primitive {
                ^
../src/cpuid.cc:52:17: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("timeStampCounter"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_TSC]));
                              ^
../src/cpuid.cc:52:24: error: 'String' does not refer to a value
                features->Set(NanNew<String>("timeStampCounter"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_TSC]));
                                     ^
/Users/daldegam/.node-gyp/4.1.1/include/node/v8.h:2081:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../src/cpuid.cc:52:53: error: use of undeclared identifier 'NanNew'
                features->Set(NanNew<String>("timeStampCounter"), NanNew<Boolean>(cpuData.flags[CPU_FEATURE_TSC]));
                                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/cpuid/src/cpuid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/daldegam/Desktop/cpuid-node
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

```

**Comment by brainling** [comment]
Done via pull request. Thanks for the bug report.
